### ISSUE TITLE
middleware層のテストパターンにリクエストヘッダの内容を検証するものを追加する

### ISSUE THREAD

**Issue by MasashiFujiike** [whalepod/milelane#27]
リクエストヘッダに対してもバリデーションがかかっているのだが、そのパターンに対するテストが現状はない。テストを手厚くすることでしっかり検証されるようにする。

**Comment by sanoyo** [comment]
>リクエストヘッダに対してもバリデーションがかかっている

ここって実装でいうとどのメソッドになりますか？
自分の方でも見てみたんですが、`CORSHeaders()` メソッドしかなく、
このメソッドでは、バリデーションというより、CORS の設定をして、適応しているように見えます。
なので、何をテストすれば良いのだろうとなっており、アドバイスいただきたいです！
